language: java
env:
  global:
  - GITHUB_REPO=symbiote-h2020/Registry
  - secure: puH8W5SfSW+wlU4OndG9hb5A4q4oB1VdtHQ6GNfkHVIrVBhd1h221QtEmuNsBNAIVVH+HgMs+UPAg3Xho8e9nqeGHurEvaJuTAzyZRZeqmYRZiaPcjtRQBS/bJ1LLDz3mf7DFlkwKWzKAXyYs1QbiCRmNBzERYzhraZdNjX9tdxAL+DNUgaZ6KI0x3Lm02zhf1YnlSJmidJ1ivTzosQ8LSuZw5ILyvS2kY7KADlCb9llOqIUPM9/B4qyahcSSGJ7HAT8589V/NK6KgPdHuvtgGNOJ+Y2TDA/3Z7TyN5nLLqJuCgs/A12d9PPzOgtI9lK463SR7jM8zFk+oohDpmZbd+8U+aJDZk8F7fs/eA2rspLgLV5Q01xsKgqDpngbyX2Psy8rmEJjqZN3qDIVnnQSdpCGtb611LRGLAA29iUxQ+i+UFU6DfzogJDj/onOoE+Lg/RmKaDtViLUhLB+mKIWGD9M7lVtMM9F0UQkxayiU4QWMIMadW+m3uOelTVCXm5poqCIsub/5Ndk4NGadpk3eI1iQ314E4NguEdYmVKG5WIruOo6t6Oj+Q2L4PJHjkGurJ3/h04SWumWBqTW7eNp05GNq96nz6WmkxqMTSYWtCFuIrkKK7Mz1BFVmnBAcRJxrJi55dP075Ua1S+BgRYvsORdu4qPhs3vVdqgfY9v38=
jdk:
- oraclejdk8
services:
- mongodb
- rabbitmq
sudo: required
branches:
  only:
  - staging
install: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_script:
- chmod a+x merge_script.sh
- "./merge_script.sh"
after_success:
- chmod a+x pushing_script.sh
- "./pushing_script.sh"
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: always
